server:
  port: 8081
  servlet:
    context-path: /payup


#数据库连接配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ''
    url: jdbc:mysql://XXXXXXXXXXXXXXX:3306/boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update


#redis配置
redis:
  host: XXXXXXXXXX
  port: 6379
  timeout: 3
  password: XXXXXXXXXXXX
  poolMaxTotal: 20
  poolMaxIdle: 10
  poolMaxWait: 3



cupSize: A
age: 18
content: "cupSize:${cupSize},age:${age}"



girl:
  cupSize: B
  age: 28
